// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package catalog

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CatalogServiceClient is the client API for CatalogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CatalogServiceClient interface {
	GetCatalogProductByID(ctx context.Context, in *GetCatalogProductByIDRequest, opts ...grpc.CallOption) (*GetCatalogProductByIDReply, error)
	GetSizeInfo(ctx context.Context, in *GetSizeInfoRequest, opts ...grpc.CallOption) (*GetSizeInfoReply, error)
	GetCurrentSeasonByPlantationID(ctx context.Context, in *GetCurrentSeasonByPlantationIDRequest, opts ...grpc.CallOption) (*GetCurrentSeasonByPlantationIDReply, error)
}

type catalogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCatalogServiceClient(cc grpc.ClientConnInterface) CatalogServiceClient {
	return &catalogServiceClient{cc}
}

func (c *catalogServiceClient) GetCatalogProductByID(ctx context.Context, in *GetCatalogProductByIDRequest, opts ...grpc.CallOption) (*GetCatalogProductByIDReply, error) {
	out := new(GetCatalogProductByIDReply)
	err := c.cc.Invoke(ctx, "/CatalogService/GetCatalogProductByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetSizeInfo(ctx context.Context, in *GetSizeInfoRequest, opts ...grpc.CallOption) (*GetSizeInfoReply, error) {
	out := new(GetSizeInfoReply)
	err := c.cc.Invoke(ctx, "/CatalogService/GetSizeInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetCurrentSeasonByPlantationID(ctx context.Context, in *GetCurrentSeasonByPlantationIDRequest, opts ...grpc.CallOption) (*GetCurrentSeasonByPlantationIDReply, error) {
	out := new(GetCurrentSeasonByPlantationIDReply)
	err := c.cc.Invoke(ctx, "/CatalogService/GetCurrentSeasonByPlantationID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatalogServiceServer is the server API for CatalogService service.
// All implementations must embed UnimplementedCatalogServiceServer
// for forward compatibility
type CatalogServiceServer interface {
	GetCatalogProductByID(context.Context, *GetCatalogProductByIDRequest) (*GetCatalogProductByIDReply, error)
	GetSizeInfo(context.Context, *GetSizeInfoRequest) (*GetSizeInfoReply, error)
	GetCurrentSeasonByPlantationID(context.Context, *GetCurrentSeasonByPlantationIDRequest) (*GetCurrentSeasonByPlantationIDReply, error)
	mustEmbedUnimplementedCatalogServiceServer()
}

// UnimplementedCatalogServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCatalogServiceServer struct {
}

func (UnimplementedCatalogServiceServer) GetCatalogProductByID(context.Context, *GetCatalogProductByIDRequest) (*GetCatalogProductByIDReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCatalogProductByID not implemented")
}
func (UnimplementedCatalogServiceServer) GetSizeInfo(context.Context, *GetSizeInfoRequest) (*GetSizeInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSizeInfo not implemented")
}
func (UnimplementedCatalogServiceServer) GetCurrentSeasonByPlantationID(context.Context, *GetCurrentSeasonByPlantationIDRequest) (*GetCurrentSeasonByPlantationIDReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrentSeasonByPlantationID not implemented")
}
func (UnimplementedCatalogServiceServer) mustEmbedUnimplementedCatalogServiceServer() {}

// UnsafeCatalogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CatalogServiceServer will
// result in compilation errors.
type UnsafeCatalogServiceServer interface {
	mustEmbedUnimplementedCatalogServiceServer()
}

func RegisterCatalogServiceServer(s grpc.ServiceRegistrar, srv CatalogServiceServer) {
	s.RegisterService(&CatalogService_ServiceDesc, srv)
}

func _CatalogService_GetCatalogProductByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCatalogProductByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetCatalogProductByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CatalogService/GetCatalogProductByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetCatalogProductByID(ctx, req.(*GetCatalogProductByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetSizeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSizeInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetSizeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CatalogService/GetSizeInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetSizeInfo(ctx, req.(*GetSizeInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetCurrentSeasonByPlantationID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentSeasonByPlantationIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetCurrentSeasonByPlantationID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CatalogService/GetCurrentSeasonByPlantationID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetCurrentSeasonByPlantationID(ctx, req.(*GetCurrentSeasonByPlantationIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CatalogService_ServiceDesc is the grpc.ServiceDesc for CatalogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CatalogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "CatalogService",
	HandlerType: (*CatalogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCatalogProductByID",
			Handler:    _CatalogService_GetCatalogProductByID_Handler,
		},
		{
			MethodName: "GetSizeInfo",
			Handler:    _CatalogService_GetSizeInfo_Handler,
		},
		{
			MethodName: "GetCurrentSeasonByPlantationID",
			Handler:    _CatalogService_GetCurrentSeasonByPlantationID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/catalog-service.proto",
}
