// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package setting

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SettingsServiceClient is the client API for SettingsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SettingsServiceClient interface {
	GetPlantationIdsWithDisplayEnabled(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetPlantationIdsWithDisplayEnabledReply, error)
	GetCargoByID(ctx context.Context, in *GetCargoByIDRequest, opts ...grpc.CallOption) (*GetCargoByIDReply, error)
	GetBasicSettings(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetBasicSettingsReply, error)
	GetCountryCode(ctx context.Context, in *GetCountryCodeRequest, opts ...grpc.CallOption) (*GetCountryCodeReply, error)
}

type settingsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSettingsServiceClient(cc grpc.ClientConnInterface) SettingsServiceClient {
	return &settingsServiceClient{cc}
}

func (c *settingsServiceClient) GetPlantationIdsWithDisplayEnabled(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetPlantationIdsWithDisplayEnabledReply, error) {
	out := new(GetPlantationIdsWithDisplayEnabledReply)
	err := c.cc.Invoke(ctx, "/SettingsService/GetPlantationIdsWithDisplayEnabled", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingsServiceClient) GetCargoByID(ctx context.Context, in *GetCargoByIDRequest, opts ...grpc.CallOption) (*GetCargoByIDReply, error) {
	out := new(GetCargoByIDReply)
	err := c.cc.Invoke(ctx, "/SettingsService/GetCargoByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingsServiceClient) GetBasicSettings(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetBasicSettingsReply, error) {
	out := new(GetBasicSettingsReply)
	err := c.cc.Invoke(ctx, "/SettingsService/GetBasicSettings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingsServiceClient) GetCountryCode(ctx context.Context, in *GetCountryCodeRequest, opts ...grpc.CallOption) (*GetCountryCodeReply, error) {
	out := new(GetCountryCodeReply)
	err := c.cc.Invoke(ctx, "/SettingsService/GetCountryCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SettingsServiceServer is the server API for SettingsService service.
// All implementations must embed UnimplementedSettingsServiceServer
// for forward compatibility
type SettingsServiceServer interface {
	GetPlantationIdsWithDisplayEnabled(context.Context, *Empty) (*GetPlantationIdsWithDisplayEnabledReply, error)
	GetCargoByID(context.Context, *GetCargoByIDRequest) (*GetCargoByIDReply, error)
	GetBasicSettings(context.Context, *Empty) (*GetBasicSettingsReply, error)
	GetCountryCode(context.Context, *GetCountryCodeRequest) (*GetCountryCodeReply, error)
	mustEmbedUnimplementedSettingsServiceServer()
}

// UnimplementedSettingsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSettingsServiceServer struct {
}

func (UnimplementedSettingsServiceServer) GetPlantationIdsWithDisplayEnabled(context.Context, *Empty) (*GetPlantationIdsWithDisplayEnabledReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlantationIdsWithDisplayEnabled not implemented")
}
func (UnimplementedSettingsServiceServer) GetCargoByID(context.Context, *GetCargoByIDRequest) (*GetCargoByIDReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCargoByID not implemented")
}
func (UnimplementedSettingsServiceServer) GetBasicSettings(context.Context, *Empty) (*GetBasicSettingsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBasicSettings not implemented")
}
func (UnimplementedSettingsServiceServer) GetCountryCode(context.Context, *GetCountryCodeRequest) (*GetCountryCodeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCountryCode not implemented")
}
func (UnimplementedSettingsServiceServer) mustEmbedUnimplementedSettingsServiceServer() {}

// UnsafeSettingsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SettingsServiceServer will
// result in compilation errors.
type UnsafeSettingsServiceServer interface {
	mustEmbedUnimplementedSettingsServiceServer()
}

func RegisterSettingsServiceServer(s grpc.ServiceRegistrar, srv SettingsServiceServer) {
	s.RegisterService(&SettingsService_ServiceDesc, srv)
}

func _SettingsService_GetPlantationIdsWithDisplayEnabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingsServiceServer).GetPlantationIdsWithDisplayEnabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SettingsService/GetPlantationIdsWithDisplayEnabled",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingsServiceServer).GetPlantationIdsWithDisplayEnabled(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettingsService_GetCargoByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCargoByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingsServiceServer).GetCargoByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SettingsService/GetCargoByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingsServiceServer).GetCargoByID(ctx, req.(*GetCargoByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettingsService_GetBasicSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingsServiceServer).GetBasicSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SettingsService/GetBasicSettings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingsServiceServer).GetBasicSettings(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettingsService_GetCountryCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCountryCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingsServiceServer).GetCountryCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SettingsService/GetCountryCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingsServiceServer).GetCountryCode(ctx, req.(*GetCountryCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SettingsService_ServiceDesc is the grpc.ServiceDesc for SettingsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SettingsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SettingsService",
	HandlerType: (*SettingsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPlantationIdsWithDisplayEnabled",
			Handler:    _SettingsService_GetPlantationIdsWithDisplayEnabled_Handler,
		},
		{
			MethodName: "GetCargoByID",
			Handler:    _SettingsService_GetCargoByID_Handler,
		},
		{
			MethodName: "GetBasicSettings",
			Handler:    _SettingsService_GetBasicSettings_Handler,
		},
		{
			MethodName: "GetCountryCode",
			Handler:    _SettingsService_GetCountryCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/setting-service.proto",
}
