// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: proto/setting-service.proto

package setting

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPlantationVisibleByCompanyIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CompanyId string `protobuf:"bytes,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
}

func (x *GetPlantationVisibleByCompanyIDRequest) Reset() {
	*x = GetPlantationVisibleByCompanyIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_setting_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPlantationVisibleByCompanyIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlantationVisibleByCompanyIDRequest) ProtoMessage() {}

func (x *GetPlantationVisibleByCompanyIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_setting_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlantationVisibleByCompanyIDRequest.ProtoReflect.Descriptor instead.
func (*GetPlantationVisibleByCompanyIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_setting_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetPlantationVisibleByCompanyIDRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

type GetPlantationVisibleByCompanyIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VisibleForAll bool `protobuf:"varint,1,opt,name=visible_for_all,json=visibleForAll,proto3" json:"visible_for_all,omitempty"`
}

func (x *GetPlantationVisibleByCompanyIDResponse) Reset() {
	*x = GetPlantationVisibleByCompanyIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_setting_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPlantationVisibleByCompanyIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlantationVisibleByCompanyIDResponse) ProtoMessage() {}

func (x *GetPlantationVisibleByCompanyIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_setting_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlantationVisibleByCompanyIDResponse.ProtoReflect.Descriptor instead.
func (*GetPlantationVisibleByCompanyIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_setting_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetPlantationVisibleByCompanyIDResponse) GetVisibleForAll() bool {
	if x != nil {
		return x.VisibleForAll
	}
	return false
}

type GetCountryNameByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetCountryNameByIDRequest) Reset() {
	*x = GetCountryNameByIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_setting_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCountryNameByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCountryNameByIDRequest) ProtoMessage() {}

func (x *GetCountryNameByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_setting_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCountryNameByIDRequest.ProtoReflect.Descriptor instead.
func (*GetCountryNameByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_setting_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetCountryNameByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetCountryNameByIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetCountryNameByIDResponse) Reset() {
	*x = GetCountryNameByIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_setting_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCountryNameByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCountryNameByIDResponse) ProtoMessage() {}

func (x *GetCountryNameByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_setting_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCountryNameByIDResponse.ProtoReflect.Descriptor instead.
func (*GetCountryNameByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_setting_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetCountryNameByIDResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetCountryCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CountryName string `protobuf:"bytes,1,opt,name=country_name,json=countryName,proto3" json:"country_name,omitempty"`
}

func (x *GetCountryCodeRequest) Reset() {
	*x = GetCountryCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_setting_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCountryCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCountryCodeRequest) ProtoMessage() {}

func (x *GetCountryCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_setting_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCountryCodeRequest.ProtoReflect.Descriptor instead.
func (*GetCountryCodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_setting_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetCountryCodeRequest) GetCountryName() string {
	if x != nil {
		return x.CountryName
	}
	return ""
}

type GetCountryCodeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CountryCode string `protobuf:"bytes,1,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
}

func (x *GetCountryCodeReply) Reset() {
	*x = GetCountryCodeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_setting_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCountryCodeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCountryCodeReply) ProtoMessage() {}

func (x *GetCountryCodeReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_setting_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCountryCodeReply.ProtoReflect.Descriptor instead.
func (*GetCountryCodeReply) Descriptor() ([]byte, []int) {
	return file_proto_setting_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetCountryCodeReply) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

type GetCargoByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CargoId string `protobuf:"bytes,1,opt,name=cargo_id,json=cargoId,proto3" json:"cargo_id,omitempty"`
}

func (x *GetCargoByIDRequest) Reset() {
	*x = GetCargoByIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_setting_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCargoByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCargoByIDRequest) ProtoMessage() {}

func (x *GetCargoByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_setting_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCargoByIDRequest.ProtoReflect.Descriptor instead.
func (*GetCargoByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_setting_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetCargoByIDRequest) GetCargoId() string {
	if x != nil {
		return x.CargoId
	}
	return ""
}

type GetCargoByIDReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ToCity          string     `protobuf:"bytes,2,opt,name=to_city,json=toCity,proto3" json:"to_city,omitempty"`
	ToCountry       string     `protobuf:"bytes,3,opt,name=to_country,json=toCountry,proto3" json:"to_country,omitempty"`
	PreInvoicePrice int32      `protobuf:"varint,4,opt,name=pre_invoice_price,json=preInvoicePrice,proto3" json:"pre_invoice_price,omitempty"`
	PathTime        int32      `protobuf:"varint,5,opt,name=path_time,json=pathTime,proto3" json:"path_time,omitempty"`
	Handlers        []*Handler `protobuf:"bytes,6,rep,name=handlers,proto3" json:"handlers,omitempty"`
}

func (x *GetCargoByIDReply) Reset() {
	*x = GetCargoByIDReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_setting_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCargoByIDReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCargoByIDReply) ProtoMessage() {}

func (x *GetCargoByIDReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_setting_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCargoByIDReply.ProtoReflect.Descriptor instead.
func (*GetCargoByIDReply) Descriptor() ([]byte, []int) {
	return file_proto_setting_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetCargoByIDReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetCargoByIDReply) GetToCity() string {
	if x != nil {
		return x.ToCity
	}
	return ""
}

func (x *GetCargoByIDReply) GetToCountry() string {
	if x != nil {
		return x.ToCountry
	}
	return ""
}

func (x *GetCargoByIDReply) GetPreInvoicePrice() int32 {
	if x != nil {
		return x.PreInvoicePrice
	}
	return 0
}

func (x *GetCargoByIDReply) GetPathTime() int32 {
	if x != nil {
		return x.PathTime
	}
	return 0
}

func (x *GetCargoByIDReply) GetHandlers() []*Handler {
	if x != nil {
		return x.Handlers
	}
	return nil
}

type Handler struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title           string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	PreCoolingPrice int32  `protobuf:"varint,3,opt,name=pre_cooling_price,json=preCoolingPrice,proto3" json:"pre_cooling_price,omitempty"`
}

func (x *Handler) Reset() {
	*x = Handler{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_setting_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Handler) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Handler) ProtoMessage() {}

func (x *Handler) ProtoReflect() protoreflect.Message {
	mi := &file_proto_setting_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Handler.ProtoReflect.Descriptor instead.
func (*Handler) Descriptor() ([]byte, []int) {
	return file_proto_setting_service_proto_rawDescGZIP(), []int{8}
}

func (x *Handler) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Handler) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Handler) GetPreCoolingPrice() int32 {
	if x != nil {
		return x.PreCoolingPrice
	}
	return 0
}

type GetBasicSettingsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                 string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Periods            []*Period `protobuf:"bytes,2,rep,name=periods,proto3" json:"periods,omitempty"`
	WorkingDays        []bool    `protobuf:"varint,3,rep,packed,name=working_days,json=workingDays,proto3" json:"working_days,omitempty"`
	OrderPayTimer      int32     `protobuf:"varint,4,opt,name=order_pay_timer,json=orderPayTimer,proto3" json:"order_pay_timer,omitempty"`
	OrderAcceptTimer   int32     `protobuf:"varint,5,opt,name=order_accept_timer,json=orderAcceptTimer,proto3" json:"order_accept_timer,omitempty"`
	ScreenRefreshTimer int32     `protobuf:"varint,6,opt,name=screen_refresh_timer,json=screenRefreshTimer,proto3" json:"screen_refresh_timer,omitempty"`
}

func (x *GetBasicSettingsReply) Reset() {
	*x = GetBasicSettingsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_setting_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBasicSettingsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBasicSettingsReply) ProtoMessage() {}

func (x *GetBasicSettingsReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_setting_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBasicSettingsReply.ProtoReflect.Descriptor instead.
func (*GetBasicSettingsReply) Descriptor() ([]byte, []int) {
	return file_proto_setting_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetBasicSettingsReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetBasicSettingsReply) GetPeriods() []*Period {
	if x != nil {
		return x.Periods
	}
	return nil
}

func (x *GetBasicSettingsReply) GetWorkingDays() []bool {
	if x != nil {
		return x.WorkingDays
	}
	return nil
}

func (x *GetBasicSettingsReply) GetOrderPayTimer() int32 {
	if x != nil {
		return x.OrderPayTimer
	}
	return 0
}

func (x *GetBasicSettingsReply) GetOrderAcceptTimer() int32 {
	if x != nil {
		return x.OrderAcceptTimer
	}
	return 0
}

func (x *GetBasicSettingsReply) GetScreenRefreshTimer() int32 {
	if x != nil {
		return x.ScreenRefreshTimer
	}
	return 0
}

type Period struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartsAt int32 `protobuf:"varint,1,opt,name=starts_at,json=startsAt,proto3" json:"starts_at,omitempty"`
	EndsAt   int32 `protobuf:"varint,2,opt,name=ends_at,json=endsAt,proto3" json:"ends_at,omitempty"`
}

func (x *Period) Reset() {
	*x = Period{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_setting_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Period) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Period) ProtoMessage() {}

func (x *Period) ProtoReflect() protoreflect.Message {
	mi := &file_proto_setting_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Period.ProtoReflect.Descriptor instead.
func (*Period) Descriptor() ([]byte, []int) {
	return file_proto_setting_service_proto_rawDescGZIP(), []int{10}
}

func (x *Period) GetStartsAt() int32 {
	if x != nil {
		return x.StartsAt
	}
	return 0
}

func (x *Period) GetEndsAt() int32 {
	if x != nil {
		return x.EndsAt
	}
	return 0
}

type GetPlantationIdsWithDisplayEnabledReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlantationIds []string `protobuf:"bytes,1,rep,name=plantation_ids,json=plantationIds,proto3" json:"plantation_ids,omitempty"`
}

func (x *GetPlantationIdsWithDisplayEnabledReply) Reset() {
	*x = GetPlantationIdsWithDisplayEnabledReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_setting_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPlantationIdsWithDisplayEnabledReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlantationIdsWithDisplayEnabledReply) ProtoMessage() {}

func (x *GetPlantationIdsWithDisplayEnabledReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_setting_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlantationIdsWithDisplayEnabledReply.ProtoReflect.Descriptor instead.
func (*GetPlantationIdsWithDisplayEnabledReply) Descriptor() ([]byte, []int) {
	return file_proto_setting_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetPlantationIdsWithDisplayEnabledReply) GetPlantationIds() []string {
	if x != nil {
		return x.PlantationIds
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_setting_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_setting_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_setting_service_proto_rawDescGZIP(), []int{12}
}

var File_proto_setting_service_proto protoreflect.FileDescriptor

var file_proto_setting_service_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x2d,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x47, 0x0a,
	0x26, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x69,
	0x73, 0x69, 0x62, 0x6c, 0x65, 0x42, 0x79, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x49, 0x44,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x61,
	0x6e, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6d,
	0x70, 0x61, 0x6e, 0x79, 0x49, 0x64, 0x22, 0x51, 0x0a, 0x27, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61,
	0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x69, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x42, 0x79,
	0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x26, 0x0a, 0x0f, 0x76, 0x69, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x5f, 0x66, 0x6f, 0x72,
	0x5f, 0x61, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x76, 0x69, 0x73, 0x69,
	0x62, 0x6c, 0x65, 0x46, 0x6f, 0x72, 0x41, 0x6c, 0x6c, 0x22, 0x2b, 0x0a, 0x19, 0x47, 0x65, 0x74,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x42, 0x79, 0x49, 0x44, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x30, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x72, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3a, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79,
	0x4e, 0x61, 0x6d, 0x65, 0x22, 0x38, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x30,
	0x0a, 0x13, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x67, 0x6f, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x49, 0x64,
	0x22, 0xca, 0x01, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x67, 0x6f, 0x42, 0x79, 0x49,
	0x44, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x6f, 0x5f, 0x63, 0x69, 0x74,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x6f, 0x43, 0x69, 0x74, 0x79, 0x12,
	0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x6f, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x2a,
	0x0a, 0x11, 0x70, 0x72, 0x65, 0x5f, 0x69, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x5f, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x70, 0x72, 0x65, 0x49, 0x6e,
	0x76, 0x6f, 0x69, 0x63, 0x65, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61,
	0x74, 0x68, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70,
	0x61, 0x74, 0x68, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x08, 0x68, 0x61, 0x6e, 0x64, 0x6c,
	0x65, 0x72, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x48, 0x61, 0x6e, 0x64,
	0x6c, 0x65, 0x72, 0x52, 0x08, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x73, 0x22, 0x5b, 0x0a,
	0x07, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x2a,
	0x0a, 0x11, 0x70, 0x72, 0x65, 0x5f, 0x63, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x5f, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x70, 0x72, 0x65, 0x43, 0x6f,
	0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x69, 0x63, 0x65, 0x22, 0xf5, 0x01, 0x0a, 0x15, 0x47,
	0x65, 0x74, 0x42, 0x61, 0x73, 0x69, 0x63, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x07, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x52, 0x07,
	0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x77, 0x6f, 0x72, 0x6b, 0x69,
	0x6e, 0x67, 0x5f, 0x64, 0x61, 0x79, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x08, 0x52, 0x0b, 0x77,
	0x6f, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x44, 0x61, 0x79, 0x73, 0x12, 0x26, 0x0a, 0x0f, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x5f, 0x70, 0x61, 0x79, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0d, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x50, 0x61, 0x79, 0x54, 0x69, 0x6d,
	0x65, 0x72, 0x12, 0x2c, 0x0a, 0x12, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x61, 0x63, 0x63, 0x65,
	0x70, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x72,
	0x12, 0x30, 0x0a, 0x14, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x5f, 0x72, 0x65, 0x66, 0x72, 0x65,
	0x73, 0x68, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x12,
	0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x69, 0x6d,
	0x65, 0x72, 0x22, 0x3e, 0x0a, 0x06, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x12, 0x1b, 0x0a, 0x09,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x73, 0x5f, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x73, 0x74, 0x61, 0x72, 0x74, 0x73, 0x41, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x65, 0x6e, 0x64,
	0x73, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x65, 0x6e, 0x64, 0x73,
	0x41, 0x74, 0x22, 0x50, 0x0a, 0x27, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x73, 0x57, 0x69, 0x74, 0x68, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61,
	0x79, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x25, 0x0a,
	0x0e, 0x70, 0x6c, 0x61, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x6c, 0x61, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x73, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x32, 0xab, 0x04,
	0x0a, 0x0f, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x56, 0x0a, 0x22, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x73, 0x57, 0x69, 0x74, 0x68, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79,
	0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a,
	0x28, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x73, 0x57, 0x69, 0x74, 0x68, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x45, 0x6e, 0x61,
	0x62, 0x6c, 0x65, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4d, 0x0a, 0x19, 0x47, 0x65, 0x74,
	0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x42, 0x79, 0x44, 0x61, 0x79, 0x50, 0x6c, 0x61, 0x6e, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x28,
	0x2e, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x73, 0x57, 0x69, 0x74, 0x68, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x45, 0x6e, 0x61, 0x62,
	0x6c, 0x65, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x38, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x43,
	0x61, 0x72, 0x67, 0x6f, 0x42, 0x79, 0x49, 0x44, 0x12, 0x14, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61,
	0x72, 0x67, 0x6f, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12,
	0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x67, 0x6f, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x32, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x42, 0x61, 0x73, 0x69, 0x63, 0x53, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16,
	0x2e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x73, 0x69, 0x63, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3e, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x14, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x64,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4d, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x72, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x42, 0x79, 0x49, 0x44, 0x12, 0x1a, 0x2e, 0x47,
	0x65, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x42, 0x79, 0x49,
	0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x72, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x74, 0x0a, 0x1f, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x6e,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x69, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x42, 0x79, 0x43,
	0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x49, 0x44, 0x12, 0x27, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6c,
	0x61, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x69, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x42,
	0x79, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x28, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x56, 0x69, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x42, 0x79, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e,
	0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x15, 0x5a, 0x13, 0x72,
	0x70, 0x63, 0x2f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x3b, 0x73, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_setting_service_proto_rawDescOnce sync.Once
	file_proto_setting_service_proto_rawDescData = file_proto_setting_service_proto_rawDesc
)

func file_proto_setting_service_proto_rawDescGZIP() []byte {
	file_proto_setting_service_proto_rawDescOnce.Do(func() {
		file_proto_setting_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_setting_service_proto_rawDescData)
	})
	return file_proto_setting_service_proto_rawDescData
}

var file_proto_setting_service_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_setting_service_proto_goTypes = []interface{}{
	(*GetPlantationVisibleByCompanyIDRequest)(nil),  // 0: GetPlantationVisibleByCompanyIDRequest
	(*GetPlantationVisibleByCompanyIDResponse)(nil), // 1: GetPlantationVisibleByCompanyIDResponse
	(*GetCountryNameByIDRequest)(nil),               // 2: GetCountryNameByIDRequest
	(*GetCountryNameByIDResponse)(nil),              // 3: GetCountryNameByIDResponse
	(*GetCountryCodeRequest)(nil),                   // 4: GetCountryCodeRequest
	(*GetCountryCodeReply)(nil),                     // 5: GetCountryCodeReply
	(*GetCargoByIDRequest)(nil),                     // 6: GetCargoByIDRequest
	(*GetCargoByIDReply)(nil),                       // 7: GetCargoByIDReply
	(*Handler)(nil),                                 // 8: Handler
	(*GetBasicSettingsReply)(nil),                   // 9: GetBasicSettingsReply
	(*Period)(nil),                                  // 10: Period
	(*GetPlantationIdsWithDisplayEnabledReply)(nil), // 11: GetPlantationIdsWithDisplayEnabledReply
	(*Empty)(nil),                                   // 12: Empty
}
var file_proto_setting_service_proto_depIdxs = []int32{
	8,  // 0: GetCargoByIDReply.handlers:type_name -> Handler
	10, // 1: GetBasicSettingsReply.periods:type_name -> Period
	12, // 2: SettingsService.GetPlantationIdsWithDisplayEnabled:input_type -> Empty
	12, // 3: SettingsService.GetActiveByDayPlantations:input_type -> Empty
	6,  // 4: SettingsService.GetCargoByID:input_type -> GetCargoByIDRequest
	12, // 5: SettingsService.GetBasicSettings:input_type -> Empty
	4,  // 6: SettingsService.GetCountryCode:input_type -> GetCountryCodeRequest
	2,  // 7: SettingsService.GetCountryNameByID:input_type -> GetCountryNameByIDRequest
	0,  // 8: SettingsService.GetPlantationVisibleByCompanyID:input_type -> GetPlantationVisibleByCompanyIDRequest
	11, // 9: SettingsService.GetPlantationIdsWithDisplayEnabled:output_type -> GetPlantationIdsWithDisplayEnabledReply
	11, // 10: SettingsService.GetActiveByDayPlantations:output_type -> GetPlantationIdsWithDisplayEnabledReply
	7,  // 11: SettingsService.GetCargoByID:output_type -> GetCargoByIDReply
	9,  // 12: SettingsService.GetBasicSettings:output_type -> GetBasicSettingsReply
	5,  // 13: SettingsService.GetCountryCode:output_type -> GetCountryCodeReply
	3,  // 14: SettingsService.GetCountryNameByID:output_type -> GetCountryNameByIDResponse
	1,  // 15: SettingsService.GetPlantationVisibleByCompanyID:output_type -> GetPlantationVisibleByCompanyIDResponse
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_setting_service_proto_init() }
func file_proto_setting_service_proto_init() {
	if File_proto_setting_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_setting_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPlantationVisibleByCompanyIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_setting_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPlantationVisibleByCompanyIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_setting_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCountryNameByIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_setting_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCountryNameByIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_setting_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCountryCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_setting_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCountryCodeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_setting_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCargoByIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_setting_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCargoByIDReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_setting_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Handler); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_setting_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBasicSettingsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_setting_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Period); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_setting_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPlantationIdsWithDisplayEnabledReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_setting_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_setting_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_setting_service_proto_goTypes,
		DependencyIndexes: file_proto_setting_service_proto_depIdxs,
		MessageInfos:      file_proto_setting_service_proto_msgTypes,
	}.Build()
	File_proto_setting_service_proto = out.File
	file_proto_setting_service_proto_rawDesc = nil
	file_proto_setting_service_proto_goTypes = nil
	file_proto_setting_service_proto_depIdxs = nil
}
